### ISSUE TITLE
add area from extended_geom

### ISSUE THREAD

**Issue by helllth** [cismet/lagis-desktop#65]
@therter added the possibility to retrieve the area and length (len) of a geometry directly from postgis. doing that we avoid inaccuracies and local calculations.

**Comment by PavelOlkhovoi** [comment]
I found couple examples with alkisLandparcel = undefined

[Barmen 117 58](http://localhost:5173/lagis-desktop/#/?gem=Barmen&flur=117&fstck=58-0)
[Barmen 1 300](http://localhost:5173/lagis-desktop/#/?gem=Barmen&flur=1&fstck=300-0
)

All lanparcels from Burg have the same problem

![chrome_o0jlDX0dPd](https://github.com/cismet/lagis-desktop/assets/55281206/e7f17177-0a6b-4095-a2a4-548545cdf3d1)
![chrome_xm6xn7PXmR](https://github.com/cismet/lagis-desktop/assets/55281206/6e3b24b3-ce67-4740-9877-9fefa68dd7d3)

**Comment by PavelOlkhovoi** [comment]
I found couple examples with alkisLandparcel = undefined
