### ISSUE TITLE
Add new logic for the checkbox Historie halten

### ISSUE THREAD

**Issue by PavelOlkhovoi** [cismet/lagis-desktop#79]
1. Remove the an Bildschirmgröße anpassen checkbox 
2. If Historie halten is true, don't change the current history object. The data should be saved to the additional slice. Add a string with selected one to title - Graph Beyenburg 13 927/0. Add a blue color to the current landpacel. If another land parcel is clicked, it should be a blue color and the root landparcel should be grey. 
3. If Historie halten is false, update a land parcel when it is selected.
![chrome_BVM7CcYOFD](https://github.com/cismet/lagis-desktop/assets/55281206/17ff2bcc-bf3a-452e-8a67-5e8e588a4ed3)

**Comment by helllth** [comment]
use `cursor: pointer`when hovering over a node in the history to illustrate that it is a click target

**Comment by helllth** [comment]
remove all tooltips
