### ISSUE TITLE
Integrate the Darstellung block the History Graph

### ISSUE THREAD

**Issue by PavelOlkhovoi** [cismet/lagis-desktop#80]
Selectors should filter the level of showing graph. 

![chrome_ili2QjS9pO](https://github.com/cismet/lagis-desktop/assets/55281206/9501a903-4f9e-45c3-82f5-e0da86a8b0a8)

**Comment by helllth** [comment]
This are the elements the controls should contain:

First Control: (Vollständig should be default)
<img width="339" alt="Screenshot 2023-10-13 at 16 59 51" src="https://github.com/cismet/lagis-desktop/assets/837211/dba6362c-af3f-4a7c-839c-71854c545fb6">


Second Control: (Alle Flurstücke should be default)

<img width="434" alt="Screenshot 2023-10-13 at 16 59 57" src="https://github.com/cismet/lagis-desktop/assets/837211/1f7eb157-6ffe-4a25-a485-63b0000a7002">
